apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: mysql-ephemeral-template
message: |-
  The following service(s) have been created in your project: ${DATABASE_SERVICE_NAME}.

         Username: ${MYSQL_USER}
         Password: ${MYSQL_PASSWORD}
    Database Name: ${MYSQL_DATABASE}
   Connection URL: mysql://${DATABASE_SERVICE_NAME}:3306/

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.
metadata:
  annotations:
    description: |-
      MySQL database service, without persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    iconClass: icon-mysql-database
    openshift.io/display-name: MySQL (Ephemeral)
    openshift.io/documentation-url: https://docs.okd.io/latest/using_images/db_images/mysql.html
    openshift.io/long-description: This template provides a standalone MySQL server
      with a database created.  The database is not stored on persistent storage,
      so any restart of the service will result in all data being lost.  The database
      name, username, and password are chosen via parameters when provisioning this
      service.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    samples.operator.openshift.io/version: 4.5.7
    tags: database,mysql
  creationTimestamp: "2020-10-28T03:26:40Z"
  labels:
    samples.operator.openshift.io/managed: "true"
  managedFields:
  - apiVersion: template.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:labels:
        .: {}
        f:template: {}
      f:message: {}
      f:metadata:
        f:annotations:
          .: {}
          f:description: {}
          f:iconClass: {}
          f:openshift.io/display-name: {}
          f:openshift.io/documentation-url: {}
          f:openshift.io/long-description: {}
          f:openshift.io/provider-display-name: {}
          f:openshift.io/support-url: {}
          f:samples.operator.openshift.io/version: {}
          f:tags: {}
        f:labels:
          .: {}
          f:samples.operator.openshift.io/managed: {}
      f:objects: {}
      f:parameters: {}
    manager: cluster-samples-operator
    operation: Update
    time: "2020-10-28T03:26:40Z"
  name: mysql-ephemeral
  namespace: openshift
  resourceVersion: "13188"
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/mysql-ephemeral
  uid: 533eb248-6782-45d7-8d81-a3deb69ebcbe
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: ${DATABASE_SERVICE_NAME}
  stringData:
    database-name: ${MYSQL_DATABASE}
    database-password: ${MYSQL_PASSWORD}
    database-root-password: ${MYSQL_ROOT_PASSWORD}
    database-user: ${MYSQL_USER}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
      recreateParams:
        post:
          failurePolicy: Abort
          execNewPod:
            command: 
            - /bin/bash
            - -c
            - hostname && sleep 10 && echo $QUERY | /opt/rh/rh-mysql80/root/usr/bin/mysql -h $MYSQL_SERVICE_HOST -u $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD -P 3306
            containerName: mysql
            env:
            - name: QUERY
              value: CREATE TABLE IF NOT EXISTS ACCOUNT(ACCOUNT_ID VARCHAR(8) NOT NULL,TYPE VARCHAR(24),DESCRIPTION VARCHAR(30),BALANCE NUMERIC(10,2),CREDIT_LINE NUMERIC(10,2),BEGIN_BALANCE NUMERIC(10,2),BEGIN_BALANCE_TIME_STAMP TIMESTAMP,CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_ID));CREATE TABLE IF NOT EXISTS CUSTOMER(CUSTOMER_ID VARCHAR(8) NOT NULL,LAST_NAME VARCHAR(30),FIRST_NAME VARCHAR(30),MIDDLE_INITIAL VARCHAR(1),STREET VARCHAR(40),CITY VARCHAR(40),STATE VARCHAR(2),ZIP VARCHAR(5),PHONE VARCHAR(16),EMAIL VARCHAR(30),CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_ID));CREATE TABLE IF NOT EXISTS TX(TX_ID VARCHAR(8) NOT NULL,ACCOUNT_ID VARCHAR(8),TIME_STAMP TIMESTAMP,AMOUNT NUMERIC(10,2),BALANCE NUMERIC(10,2),DESCRIPTION VARCHAR(30),CONSTRAINT PK_TX PRIMARY KEY(TX_ID));CREATE TABLE IF NOT EXISTS CUSTOMER_ACCOUNT_XREF(CUSTOMER_ID VARCHAR(8),ACCOUNT_ID VARCHAR(8));CREATE TABLE IF NOT EXISTS NEXT_ID(BEANNAME VARCHAR(30) NOT NULL,ID NUMERIC,CONSTRAINT PK_NEXTID PRIMARY KEY(BEANNAME));INSERT INTO ACCOUNT VALUES('5005','Money Market','Hi Balance',3300.00,0.00,3500.00,'2003-07-28 23:03:20.000000000');INSERT INTO ACCOUNT VALUES('5006','Checking','Checking',2458.32,0.00,66.54,'2003-07-21 03:12:00.000000000');INSERT INTO ACCOUNT VALUES('5007','Credit','Visa',220.03,5000.00,166.08,'2003-07-23 10:13:54.000000000');INSERT INTO ACCOUNT VALUES('5008','Savings','Super Interest Account',59601.35,0.00,5433.89,'2003-07-15 12:55:33.000000000');INSERT INTO CUSTOMER VALUES('200','Jones','Richard','K','88 Poplar Ave.','Cupertino','CA','95014','408-123-4567','rhill@j2ee.com');INSERT INTO CUSTOMER VALUES('201','Jones','Mary','R','88 Poplar Ave.','Cupertino','CA','95014','408-123-4567','mhill@j2ee.com');INSERT INTO TX VALUES('1','5005','2003-09-01 13:00:30.000000000',200.00,4200.00,'Refund');INSERT INTO TX VALUES('10','5008','2003-09-10 13:00:30.000000000',1000.00,55601.35,'Deposit');INSERT INTO TX VALUES('11','5007','2003-09-11 13:00:30.000000000',585.00,970.08,'Airplane Tickets');INSERT INTO TX VALUES('12','5006','2003-09-12 13:00:30.000000000',-675.00,2210.00,'Mortgage Payment');INSERT INTO TX VALUES('13','5005','2003-09-13 13:00:30.000000000',-100.00,3900.00,'ATM Withdrawal');INSERT INTO TX VALUES('14','5006','2003-09-14 13:00:30.000000000',-385.08,1824.92,'Visa Payment');INSERT INTO TX VALUES('15','5007','2003-09-15 13:00:30.000000000',-385.08,585.00,'Payment');INSERT INTO TX VALUES('17','5007','2003-09-17 13:00:30.000000000',26.95,611.95,'Movies');INSERT INTO TX VALUES('18','5006','2003-09-18 13:00:30.000000000',-31.00,1793.92,'Groceries');INSERT INTO TX VALUES('19','5005','2003-09-19 13:00:30.000000000',-150.00,3750.00,'ATM Withdrawal');INSERT INTO TX VALUES('20','5006','2003-09-20 13:00:30.000000000',2000.00,3173.92,'Paycheck Deposit');INSERT INTO TX VALUES('21','5007','2003-09-21 13:00:30.000000000',124.00,735.95,'Furnishings');INSERT INTO TX VALUES('23','5007','2003-09-23 13:00:30.000000000',33.12,769.07,'Hardware');INSERT INTO TX VALUES('24','5006','2003-09-24 13:00:30.000000000',-175.33,2998.59,'Utility Bill');INSERT INTO TX VALUES('25','5006','2003-09-25 13:00:30.000000000',-123.00,2875.59,'Groceries');INSERT INTO TX VALUES('26','5006','2003-09-26 13:00:30.000000000',-675.00,2200.59,'Mortgage Payment');INSERT INTO TX VALUES('27','5007','2003-09-27 13:00:30.000000000',24.72,793.79,'Cafe');INSERT INTO TX VALUES('28','5008','2003-09-28 13:00:30.000000000',1000.00,56601.35,'Deposit');INSERT INTO TX VALUES('29','5007','2003-09-29 13:00:30.000000000',35.00,828.79,'Hair Salon');INSERT INTO TX VALUES('3','5008','2003-09-03 13:01:30.000000000',-1000.00,54601.35,'Transfer Out');INSERT INTO TX VALUES('30','5006','2003-09-30 13:00:30.000000000',-20.00,2180.59,'Gasoline');INSERT INTO TX VALUES('31','5005','2003-10-01 12:55:33.000000000',-100.00,3650.00,'ATM Withdrawal');INSERT INTO TX VALUES('32','5006','2003-10-02 12:55:33.000000000',-56.87,2123.72,'Phone Bill');INSERT INTO TX VALUES('33','5007','2003-10-03 12:55:33.000000000',67.99,896.78,'Acme Shoes');INSERT INTO TX VALUES('35','5007','2003-10-05 12:55:33.000000000',24.00,920.78,'Movies');INSERT INTO TX VALUES('36','5006','2003-10-06 12:55:33.000000000',2000.00,4123.72,'Paycheck Deposit');INSERT INTO TX VALUES('38','5006','2003-10-08 12:55:33.000000000',-100.00,4023.72,'Groceries');INSERT INTO TX VALUES('39','5007','2003-10-09 12:55:33.000000000',26.95,947.73,'Pizza');INSERT INTO TX VALUES('4','5006','2003-09-03 13:02:30.000000000',1000.00,1085.00,'Transfer In');INSERT INTO TX VALUES('41','5007','2003-10-11 12:55:33.000000000',125.00,1072.73,'Dentist');INSERT INTO TX VALUES('42','5006','2003-10-12 12:55:33.000000000',-675.00,3348.72,'Mortgage Payment');INSERT INTO TX VALUES('43','5005','2003-10-13 12:55:33.000000000',-150.00,3500.00,'ATM Withdrawal');INSERT INTO TX VALUES('44','5006','2003-10-14 12:55:33.000000000',-947.73,2400.99,'Visa Payment');INSERT INTO TX VALUES('45','5007','2003-10-15 12:55:33.000000000',-947.73,125.00,'Payment');INSERT INTO TX VALUES('47','5007','2003-10-17 12:55:33.000000000',49.90,100.85,'Bookstore');INSERT INTO TX VALUES('48','5006','2003-10-18 12:55:33.000000000',-100.00,2300.99,'Groceries');INSERT INTO TX VALUES('5','5007','2003-09-05 13:03:30.000000000',33.00,199.08,'Clothing');INSERT INTO TX VALUES('50','5006','2003-10-20 12:55:33.000000000',2000.00,4300.99,'Paycheck Deposit');INSERT INTO TX VALUES('51','5007','2003-10-21 12:55:33.000000000',80.32,181.17,'Restaurant');INSERT INTO TX VALUES('53','5007','2003-10-23 12:55:33.000000000',11.78,192.95,'Electronics');INSERT INTO TX VALUES('54','5006','2003-10-24 12:55:33.000000000',-150.45,4150.54,'Utility Bill');INSERT INTO TX VALUES('55','5005','2003-10-25 12:55:33.000000000',-100.00,3400.00,'ATM Withdrawal');INSERT INTO TX VALUES('56','5006','2003-10-26 12:55:33.000000000',-675.00,3475.54,'Mortgage Payment');INSERT INTO TX VALUES('57','5007','2003-10-27 12:55:33.000000000',24.00,216.95,'Ice Skating');INSERT INTO TX VALUES('58','5006','2003-10-28 12:55:33.000000000',-1000.00,2475.54,'Transfer Out');INSERT INTO TX VALUES('59','5008','2003-10-28 12:55:33.000000000',1000.00,57601.35,'Transfer In');INSERT INTO TX VALUES('6','5006','2003-09-06 13:04:30.000000000',2000.00,3085.00,'Paycheck Deposit');INSERT INTO TX VALUES('60','5006','2003-11-02 12:55:33.000000000',-99.22,3376.32,'Phone Bill');INSERT INTO TX VALUES('61','5007','2003-11-03 12:55:33.000000000',29.97,246.92,'Toy Store');INSERT INTO TX VALUES('62','5006','2003-11-04 12:55:33.000000000',-2000.00,376.32,'Transfer Out');INSERT INTO TX VALUES('63','5008','2003-11-05 12:55:33.000000000',2000.00,59601.35,'Transfer In');INSERT INTO TX VALUES('64','5006','2003-11-06 12:55:33.000000000',2000.00,2376.32,'Paycheck Deposit');INSERT INTO TX VALUES('65','5007','2003-11-07 12:55:33.000000000',14.69,261.61,'Cafe');INSERT INTO TX VALUES('66','5006','2003-11-08 12:55:33.000000000',-108.99,2267.33,'Groceries');INSERT INTO TX VALUES('67','5006','2003-11-09 12:55:33.000000000',-30.12,2237.21,'Gasoline');INSERT INTO TX VALUES('69','5007','2003-11-11 12:55:33.000000000',125.00,386.61,'Dentist');INSERT INTO TX VALUES('7','5005','2003-09-07 13:05:30.000000000',-200.00,4000.00,'ATM Withdrawal');INSERT INTO TX VALUES('70','5006','2003-11-12 12:55:33.000000000',-675.00,1562.21,'Mortgage Payment');INSERT INTO TX VALUES('72','5006','2003-11-13 12:55:33.000000000',-261.61,1300.60,'Visa Payment');INSERT INTO TX VALUES('73','5007','2003-11-14 12:55:33.000000000',-261.61,125.00,'Payment');INSERT INTO TX VALUES('75','5007','2003-11-15 12:55:33.000000000',24.00,149.00,'Drug Store');INSERT INTO TX VALUES('76','5006','2003-11-16 12:55:33.000000000',-67.98,1232.62,'Groceries');INSERT INTO TX VALUES('78','5006','2003-11-17 12:55:33.000000000',2000.00,3232.62,'Paycheck Deposit');INSERT INTO TX VALUES('79','5007','2003-11-18 12:55:33.000000000',32.95,181.95,'CDs');INSERT INTO TX VALUES('8','5006','2003-09-08 13:06:30.000000000',-200.00,2885.00,'Car Insurance');INSERT INTO TX VALUES('81','5007','2003-11-20 12:55:33.000000000',14.10,196.05,'Sports Store');INSERT INTO TX VALUES('82','5006','2003-11-21 12:55:33.000000000',-99.30,3133.32,'Utility Bill');INSERT INTO TX VALUES('84','5006','2003-11-21 12:55:33.000000000',-675.00,2458.32,'Mortgage Payment');INSERT INTO TX VALUES('85','5007','2003-11-22 12:55:33.000000000',23.98,220.03,'Garden Supply');INSERT INTO TX VALUES('86','5005','2003-11-23 12:55:33.000000000',-100.00,3300.00,'ATM Withdrawal');INSERT INTO TX VALUES('9','5007','2003-09-09 13:07:30.000000000',186.00,385.08,'Car Repair');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('200','5005');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('201','5005');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('200','5006');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('200','5007');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('201','5006');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('201','5007');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('200','5008');INSERT INTO CUSTOMER_ACCOUNT_XREF VALUES('201','5008');INSERT INTO NEXT_ID VALUES('account',5050);INSERT INTO NEXT_ID VALUES('customer',202);INSERT INTO NEXT_ID VALUES('tx',100);
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${DATABASE_SERVICE_NAME}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ${DATABASE_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ""
          name: ${DATABASE_SERVICE_NAME}-data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:${MYSQL_VERSION}
          namespace: ${NAMESPACE}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql
- description: Username for MySQL user that will be used for accessing the database.
  displayName: MySQL Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: MYSQL_USER
  required: true
- description: Password for the MySQL connection user.
  displayName: MySQL Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_PASSWORD
  required: true
- description: Password for the MySQL root user.
  displayName: MySQL root user Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Name of the MySQL database accessed.
  displayName: MySQL Database Name
  name: MYSQL_DATABASE
  required: true
  value: sampledb
- description: Version of MySQL image to be used (8.0, or latest).
  displayName: Version of MySQL Image
  name: MYSQL_VERSION
  required: true
  value: "5.7"
